#database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # You must write the database name you created on your PC
    url: jdbc:mysql://localhost:3308/fairy-tale-island?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # You must write the user account information you created in mysql.
    username: root
    password: rootpassword
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  #  thymeleaf:
  #    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update # table 계속 drop하지 않도록 create -> update로 바꿈.

  # oauth 설정
  profiles:
    include:
      - oauth
      - API-KEY
      - chatgpt
    group:
      "local": "local, jwt, oauth"
    active: local